server:
  port: 8081

spring:
  application:
    name: PAYMENT-SERVICE


  logging:
    level:
      io.github.resilience4j.retry: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    register-with-eureka: true
    fetch-registry: true

resilience4j:

  ratelimiter:
    instances:
      shippingRateLimiter:
        # Number of requests allowed during one refresh period
        limitForPeriod: 5
        # Bucket refill interval
        limitRefreshPeriod: 10s
        # How long to wait for a permit
        timeoutDuration: 0
  retry:
    instances:
      shippingRetry:
        retryAspectOrder: 1
        maxAttempts: 3
        waitDuration: 2s

  circuitbreaker:
    instances:
      shippingServiceCircuit:
        circuitBreakerAspectOrder: 2
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 2


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,circuitbreakerevents,retry,retryevents,loggers,threaddump